### ISSUE TITLE
Hard Coded UID + GID in Dockerfile

### ISSUE THREAD

**Issue by f35f0ef9d0e827dae86552d3899f78fc** [ich777/docker-terraria-server#1]
The Dockerfile has UID and GID hard coded. Since those parameters are not tokenized, the mounted host path must allow UID 99 and GID 100. I tried to overwrite with this in the docker run line:
```
--env 'UID=1000'
--env 'GID=1000'
```
It does not work. The container will crash with logs like below:

```
---Start Server---
tail: cannot open '/serverdata/serverfiles/masterLog.0' for reading: No such file or directory
tail: no files remaining
---Setting umask to 000---
---Version Check---
---Terraria not found, downloading!---
unzip:  cannot find or open /serverdata/serverfiles/terraria-server-1353.zip, /serverdata/serverfiles/terraria-server-1353.zip.zip or /serverdata/serverfiles/terraria-server-1353.zip.ZIP.
mv: cannot stat '/serverdata/serverfiles/1353/Linux/*': No such file or directory
rm: cannot remove '/serverdata/serverfiles/1353': No such file or directory
rm: cannot remove '/serverdata/serverfiles/terraria-server-1353.zip': No such file or directory
---Prepare Server---
---No serverconfig.txt found, downloading...---
---Server ready---
chmod: changing permissions of '/serverdata/serverfiles': Operation not permitted
```
The only way I could get the container to run was to:
1. `chmod 99:100 /host/path`
1. Remove the UID and GID env parameters from docker run line

Furthermore, I do not agree with this line in the startup script:
`chmod -R 777 ${DATA_DIR}`

Most files do not need to be writeable and **should not** be. I would prefer to have the mounted host path more secure than this!

**Comment by ich777** [comment]
Thrid to change the UID and GID, works fine on my Unraid server, can you try to set another UMASK variable like and post the output of the log again:

`--env 'UMASK=001' `
(only to check if you change that value)

The next thing that i've see is that the container can't find the downloaded zip file (btw sorry i've forgotten to include a check if the download was successful - will update the container in a few days) also please set the variable for the version like this with dot's:
`--env 'GAME_VERSION=1.3.5.3' `

As for the permissions, the container runs Terraria as a non root user and therefore it should not be a securtiy issue, i made this more because that the directory is read and writable on the host and since this is all containerized it should not be a security issue - otherwise if i doesn't change the permissions you can't edit your config the easy way...

Please report back about the UMASK variable and include the server startup log.

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment]
I'll give it a shot and report back. I have an in-development revision here, where I changed the UMASK as well:
https://gitlab.com/wroot/docker-terraria/blob/development/Dockerfile

**Comment by ich777** [comment]
But you hardcode the GID in your Dockerfile:

`RUN groupadd --gid 1000 terraria`

Is it possible that the GID 1000 and UID 1000 doesn't exist on your host machine or that it requires higher privileges?

Also if you can run easily into issues if you don't make the whole directory readable, think of mods or anything else, again because this container runs on non root privileges and is isolated from the host it should be no problem.

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment]
I shouldn't have referenced my edition of your work since it's still in the works.

Aside from that, I am going to close this issue for now since I cannot easily participate. My main computer died and I don't want to set my laptop up for this kind of stuff. I will hopefully come back in a few weeks.
