### ISSUE TITLE
Prepend timestamps to log

### ISSUE THREAD

**Issue by shadow7412** [ich777/docker-terraria-server#11]
It would be useful, particularly when knowing about when the game last saved, what times of the day are safer for updates, etc.

This stack overflow has some good ideas about doing this quickly: https://unix.stackexchange.com/questions/26728/prepending-a-timestamp-to-each-line-of-output-from-a-command

**Comment by ich777** [comment]
@shadow7412 yes, that would be of course helpful to see the timestamp when the game is saved but this is something you have to request from the developers from Terraria.

The main issue with the linked solutions is that Terraria won't work with `ts` AFAIK since you can't pipe the output through something else, in the case of Terraria.

This is a feature that needs to be requested on the Terraria forums over [here](https://forums.terraria.org/index.php?threads/feature-requests.62428/). I think you can even contact the developers over Twitter and they will answer pretty quickly.

**Comment by shadow7412** [comment]
I thought you could have updated the tail command which watches the log.

**Comment by ich777** [comment]
> I thought you could have updated the tail command which watches the log.

No, that's not possible, at least not with the solutions from above.
Why not request it from the Terraria developers themselves?

**Comment by shadow7412** [comment]
Figured it would be a quick fix. I'm not opposed to asking though.
