### ISSUE TITLE
tModLoader 64 support

### ISSUE THREAD

**Issue by sclark-dev** [ich777/docker-terraria-server#3]
Recently tModLoader64 was updated to match the latest build of TML, so I was hoping it would be possible to add support for that. I've actually forked and made a new branch for TML64 with all the modified code, but I'm unsure if it's possible to merge a forked branch.

If so, just let me know. Otherwise, feel free to pull from my fork.
https://github.com/ff-sclark/docker-terraria-server/tree/tmodloader64

**Comment by ff-sclark** [comment]
TML64 does some patches to TML that allows the server to use more than 2GB of memory. Terraria and TML are both 32-bit applications so they will crash if you attempt to use more memory than 2GB. This is surprisingly easy with large mods or many players.

From what I can see, TML only supports Windows natively. It uses a modified Mono to run on UNIX machines. This modified Mono does support 64-bit, but the TML executables themselves are still 32-bit. I'm looking into the possibility of running TML64 through the included Mono, so there isn't a need to install it.

I'm also not sure if all TML files are required for TML64, but since the container downloads the whole release, trying to minimize that would be more work than it's worth.

The modifications I made were quite messy as they were mostly intended for a "will this even run?".

**Comment by ff-sclark** [comment]
I've been running this on Unraid, although most bug testing is done through Docker CLI on Windows.

Integrating TML64 as a toggle option might be the way to go, as none of the executables are actually pre-packaged with the image. This also means it's much easier to swap between 32 and 64 without having to swap containers. Plus less maintenance.

I actually just noticed that Terraria as a whole only natively supports Windows. Even just the basic server uses MonoKickstart. After some tweaks, I have TML64 using the version of Mono that is included with Terraria and TML, and it seems to run fine. I'll be testing this over the next couple of days to make sure it doesn't randomly break.

If this works, it means there isn't any need for Mono, and TML64 support can easily be added.
