### ISSUE TITLE
serverconfig.txt & world.zip

### ISSUE THREAD

**Issue by sclark-dev** [ich777/docker-terraria-server#9]
When the container is started for the first time, it downloads the serverconfig.txt, and world.zip.

The serverconfig.txt should be updated to show the new options that came with 1.4.

As for the world.zip, it's better to let Terraria generate the world itself. If the world.zip is from an older version, new generation features are missing, and if you try loading a newer world with an older server, it causes a crash.

**Comment by ich777** [comment]
@sclark-dev that's a thing for another day, will fix that ASAP.

I don't remember exactly but I had an issue where the server actually crashed if it had to auto generate it and no world was in place, that's why I did it that way.
But like I saw today on the mobile version from Terraria it works just fine. Maybe there was a issue back then.

Will test this and also change that if everything is working.

**Comment by ich777** [comment]
Everything done and updated, thank you as always for the PRs and heads up.
